### ISSUE TITLE
There is no need to trigger progress while creating the temp file

### ISSUE THREAD

**Issue by Un-0wn** [TechShreyash/techzdl#2]
There is no need to trigger progress while creating the temp file, because the progress goes directly from 1 to 100 when the temp file is created for the first time.

**Comment by TechShreyash** [comment]
Yeah sure for small files it doesnt matter

But for large files, consider a 6gb file, its necessary to update the progress or user would think the program is stuck

If you dont want, just check in your callback for the status message is downloading or not

**Comment by Un-0wn** [comment]
But this cannot be run on production level, user has no idea about temporary file progress,

or write something like 'disable temp file progress'

**Comment by TechShreyash** [comment]
@Un-0wn It's crucial to show progress to users. For instance, on my TG Drive website, creating a file of 3 or 4 GB typically takes 10 to 15 seconds. Failing to show progress during this time could give the impression that the program has frozen.

Rather than using 'temporary file progress' as status message, consider alternatives such as 'starting download' or 'processing your file'.

Regarding 'disable temp file progress', it's better not to add that in techz. Instead, you should modify this in your callback function.
